name: money_manager_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  camera:
  path_provider:
  path:
  gallery_saver: ^2.3.2
  image_picker: 0.8.6
  http: 0.13.5
  uuid: 3.0.6
  flutter_native_image: ^0.0.6+1
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
